### ISSUE TITLE
Load/Store Data From/To Database

### ISSUE THREAD

**Issue by penghou620** [GatechVIP/no-code#35] opened 2013-03-07 01:06 UTC
stuart:
We use helenus as a client to cassandra for data persistance. In Hilary we then write a dao.js to abstract that into an api, you can see an example at 

https://github.com/sakaiproject/Hilary/blob/master/node_modules/oae-content/lib/internal/dao.content.js

**Comment by wbbarr** [comment] 2013-03-13 23:07
Closed as duplicate of https://github.com/GatechVIP/no-code/issues/34

**Closed as completed by wbbarr** 2013-03-13 23:07 UTC
Labels: Backend
